// Auto-generated from breakout.com.pk scrape — real CDN images
const HERO_SLIDES = [
  {
    "desktop": "https://www.breakout.com.pk/cdn/shop/files/Men_Main_jpg_68c3ab17-7192-4bf0-a758-e73897e8869a.jpg?v=1786734994&width=2560",
    "mobile": "https://www.breakout.com.pk/cdn/shop/files/Men_Mobile_jpg_7b3d3cb0-6622-4180-9ec7-3ab0803d54a1.jpg?v=1786734989&width=1000",
    "link": "#section-men"
  },
  {
    "desktop": "https://www.breakout.com.pk/cdn/shop/files/Women_Main_jpg_c97ae766-5dc7-4ade-84fc-df59a3bf5c97.jpg?v=1786734994&width=2560",
    "mobile": "https://www.breakout.com.pk/cdn/shop/files/Women_Mobile_jpg_97c99a29-9979-491a-9168-8cb618335c8e.jpg?v=1786734988&width=1000",
    "link": "#section-women"
  },
  {
    "desktop": "https://www.breakout.com.pk/cdn/shop/files/Boy_Main_Banners_jpg_0c6da39b-c4d7-4eb1-b703-77d4d9e2a84a.jpg?v=1786734995&width=2560",
    "mobile": "https://www.breakout.com.pk/cdn/shop/files/Boy_Mobile_jpg_264a4519-1878-40fb-a5ca-31c8d355b1e2.jpg?v=1786734988&width=1000",
    "link": "#section-boys"
  },
  {
    "desktop": "https://www.breakout.com.pk/cdn/shop/files/Girl_Main_Banners_jpg_86e83b3d-6905-4d8b-bd5f-35f88040780d.jpg?v=1786734994&width=2560",
    "mobile": "https://www.breakout.com.pk/cdn/shop/files/Girl_Mobile_jpg_0542e730-8aa4-47cd-8207-d7fc4a121f1b.jpg?v=1786734988&width=1000",
    "link": "#section-girls"
  }
];

const MEGA_MENU = {
  "male": {
    "highlights": [
      "NEW ARRIVALS",
      "SPECIAL PRICE"
    ],
    "clothing": [
      "Tees",
      "Polos",
      "Summer Knits",
      "Shirts",
      "Sweaters",
      "Sweatshirts / Hoodies",
      "Jeans",
      "Cargo Pants",
      "Trousers / Chinos",
      "Joggers",
      "Shorts",
      "Co-ords"
    ],
    "accessories": [
      "Shoes",
      "Jewellery",
      "Caps / Hats",
      "Sunglasses",
      "Perfumes",
      "Bags",
      "Belts",
      "Wallets",
      "Socks",
      "Underwears / Vests"
    ],
    "collections": [
      "MIND THE GAP",
      "REMIX"
    ]
  },
  "female": {
    "highlights": [
      "NEW ARRIVALS",
      "SPECIAL PRICE"
    ],
    "clothing": [
      "Knit Tops / Tees",
      "Shirts / Dresses",
      "Sweatshirts / Hoodies",
      "Denims & Trousers",
      "Co-ords"
    ],
    "accessories": [
      "Shoes",
      "Jewellery",
      "Bags",
      "Perfumes",
      "Scarves",
      "Glasses",
      "Caps / Hats",
      "Socks",
      "Nail Polish"
    ],
    "collections": [
      "MIND THE GAP",
      "REMIX"
    ]
  },
  "boys": {
    "highlights": [
      "NEW ARRIVALS",
      "SPECIAL PRICE"
    ],
    "clothing": [
      "Tees",
      "Polos",
      "Shirts",
      "Jeans",
      "Trousers / Chinos",
      "Shorts",
      "Cargo Pants / Shorts",
      "Co-ords",
      "Character Shop"
    ],
    "accessories": [
      "Shoes",
      "Gloves",
      "Caps / Hats",
      "Socks",
      "Perfumes / Mists",
      "Belts",
      "Watches",
      "Sunglasses",
      "Boxers"
    ],
    "collections": [
      "PRE-FALL",
      "made for endless play"
    ]
  },
  "girls": {
    "highlights": [
      "NEW ARRIVALS",
      "SPECIAL PRICE"
    ],
    "clothing": [
      "Tees / Tops",
      "Shirts / Frocks",
      "Jeans / Denim",
      "Trousers",
      "Skirts",
      "Shorts",
      "Tights",
      "Co-ords",
      "Character Shop"
    ],
    "accessories": [
      "Shoes",
      "Gloves",
      "Caps / Hats",
      "Socks",
      "Perfumes / Mists",
      "Bags",
      "Belts",
      "Watches",
      "Sunglasses"
    ],
    "collections": [
      "PRE-FALL",
      "made for endless play"
    ]
  }
};

const GENDERS = [
  { id: "male", slug: "men", label: "MEN", nav: "Men" },
  { id: "female", slug: "women", label: "WOMEN", nav: "Women" },
  { id: "boys", slug: "boys", label: "BOYS", nav: "Boys" },
  { id: "girls", slug: "girls", label: "GIRLS", nav: "Girls" },
];

const FEATURED_CATEGORIES = {
  male: [
    { id: "tees", label: "MEN TEES" },
    { id: "shirts", label: "MEN SHIRTS" },
    { id: "denims", label: "MEN DENIMS" },
    { id: "trousers", label: "MEN TROUSERS/CHINOS" },
  ],
  female: [
    { id: "knit", label: "WOMEN KNIT TOPS / TEES" },
    { id: "shirts", label: "WOMEN SHIRTS / DRESSES" },
    { id: "denims", label: "WOMEN DENIMS / TROUSERS" },
    { id: "coords", label: "WOMEN CO-ORDS" },
  ],
  boys: [
    { id: "tees", label: "BOYS TEES" },
    { id: "shirts", label: "BOYS SHIRTS" },
    { id: "bottoms", label: "BOYS BOTTOMS" },
    { id: "coords", label: "BOYS CO-ORDS" },
  ],
  girls: [
    { id: "tops", label: "GIRLS TEES / TOPS" },
    { id: "frocks", label: "GIRLS SHIRTS / FROCKS" },
    { id: "bottoms", label: "GIRLS BOTTOMS" },
    { id: "coords", label: "GIRLS CO-ORDS" },
  ],
};

const PRODUCTS = [
  {
    "id": "relaxed-fit-linen-shirt",
    "name": "RELAXED FIT LINEN SHIRT",
    "gender": "male",
    "featuredCategory": "shirts",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6DSFW667-BLU_4.jpg?v=1779176897&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "boxy-fit-zip-embroidered-polo",
    "name": "BOXY FIT ZIP EMBROIDERED POLO",
    "gender": "male",
    "featuredCategory": "tees",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6DSHP806-BGE_2.jpg?v=1781677513&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "contrast-rib-super-soft-tee",
    "name": "CONTRAST RIB SUPER SOFT TEE",
    "gender": "male",
    "featuredCategory": "tees",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6DSHT691-DRS_2.jpg?v=1781677478&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "stretch-cropped-fit-denim",
    "name": "STRETCH CROPPED FIT DENIM",
    "gender": "male",
    "featuredCategory": "denims",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6DSMD802-BLK_1.jpg?v=1782107744&width=840",
    "category": "lower_body",
    "garment_type": "jeans"
  },
  {
    "id": "cardio-tank",
    "name": "CARDIO TANK",
    "gender": "male",
    "featuredCategory": "tees",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6DSST810-WHT_1.jpg?v=1782210223&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "baggy-fit-graphic-tee",
    "name": "BAGGY FIT GRAPHIC TEE",
    "gender": "male",
    "featuredCategory": "tees",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESHT836-KHK_5.jpg?v=1786452091&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "textured-striped-tee",
    "name": "TEXTURED STRIPED TEE",
    "gender": "male",
    "featuredCategory": "tees",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESHT832-WHT_1.jpg?v=1786452082&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "textured-tee",
    "name": "TEXTURED TEE",
    "gender": "male",
    "featuredCategory": "tees",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESHT831L-BLK_4.jpg?v=1786454279&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "relaxed-fit-cloud-feel-tee",
    "name": "RELAXED FIT CLOUD FEEL TEE",
    "gender": "male",
    "featuredCategory": "tees",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESHT821-WHT_4.jpg?v=1786513574&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "boxy-fit-tee",
    "name": "BOXY FIT TEE",
    "gender": "male",
    "featuredCategory": "tees",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESHT820-OLV_1.jpg?v=1786513608&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "baggy-fit-shirt",
    "name": "BAGGY FIT SHIRT",
    "gender": "male",
    "featuredCategory": "shirts",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESHW833-STN_1.jpg?v=1786452058&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "baggy-fit-check-shirt",
    "name": "BAGGY FIT CHECK SHIRT",
    "gender": "male",
    "featuredCategory": "shirts",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESFW855-PGN_5.jpg?v=1786537915&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "button-down-dobby-shirt",
    "name": "BUTTON DOWN DOBBY SHIRT",
    "gender": "male",
    "featuredCategory": "shirts",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESFW843-SBU_4.jpg?v=1786513456&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "button-down-check-shirt",
    "name": "BUTTON DOWN CHECK SHIRT",
    "gender": "male",
    "featuredCategory": "shirts",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESFW817-STN_4.jpg?v=1786513486&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "slim-relaxed-fit-denim",
    "name": "SLIM RELAXED FIT DENIM",
    "gender": "male",
    "featuredCategory": "denims",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESMD869-LBU_1.jpg?v=1787297102&width=840",
    "category": "lower_body",
    "garment_type": "jeans"
  },
  {
    "id": "regular-fit-denim",
    "name": "REGULAR FIT DENIM",
    "gender": "male",
    "featuredCategory": "denims",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESMD818-BLU_1_3a538e73-a102-4c0c-8e6f-467b4c5ca686.jpg?v=1787047085&width=840",
    "category": "lower_body",
    "garment_type": "jeans"
  },
  {
    "id": "wide-leg-fit-denim",
    "name": "WIDE LEG FIT DENIM",
    "gender": "male",
    "featuredCategory": "denims",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESMD842-BLU_1.jpg?v=1786537687&width=840",
    "category": "lower_body",
    "garment_type": "jeans"
  },
  {
    "id": "original-straight-fit-cargo-denim",
    "name": "ORIGINAL STRAIGHT FIT CARGO DENIM",
    "gender": "male",
    "featuredCategory": "denims",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESMD840-BLU_1_5327bf4c-8367-4481-926d-7736b84efddd.jpg?v=1786453667&width=840",
    "category": "lower_body",
    "garment_type": "jeans"
  },
  {
    "id": "original-straight-fit-denim",
    "name": "ORIGINAL STRAIGHT FIT DENIM",
    "gender": "male",
    "featuredCategory": "denims",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESMD859-BLK_1.jpg?v=1786537650&width=840",
    "category": "lower_body",
    "garment_type": "jeans"
  },
  {
    "id": "carrot-fit-denim",
    "name": "CARROT FIT DENIM",
    "gender": "male",
    "featuredCategory": "denims",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESMD866-BLU_1.jpg?v=1786537651&width=840",
    "category": "lower_body",
    "garment_type": "jeans"
  },
  {
    "id": "slim-relaxed-fit-trouser",
    "name": "SLIM RELAXED FIT TROUSER",
    "gender": "male",
    "featuredCategory": "trousers",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESMT851-BLK_1.jpg?v=1786537562&width=840",
    "category": "lower_body",
    "garment_type": "trouser"
  },
  {
    "id": "wide-leg-fit-trouser",
    "name": "WIDE LEG FIT TROUSER",
    "gender": "male",
    "featuredCategory": "trousers",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESMT864-OLV_1.jpg?v=1786537557&width=840",
    "category": "lower_body",
    "garment_type": "trouser"
  },
  {
    "id": "loose-fit-carpenter-trouser",
    "name": "LOOSE FIT CARPENTER TROUSER",
    "gender": "male",
    "featuredCategory": "trousers",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESMT830-STN_1_f65c27b4-ad11-44f7-a7cd-93296446710b.jpg?v=1786452834&width=840",
    "category": "lower_body",
    "garment_type": "trouser"
  },
  {
    "id": "printed-button-down-shirt",
    "name": "PRINTED BUTTON DOWN SHIRT",
    "gender": "male",
    "featuredCategory": "shirts",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6DSWT912-MTO_6.jpg?v=1782899185&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "straight-fit-denim",
    "name": "STRAIGHT FIT DENIM",
    "gender": "male",
    "featuredCategory": "denims",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6DSWD778-WHT_1.jpg?v=1781265450&width=840",
    "category": "lower_body",
    "garment_type": "jeans"
  },
  {
    "id": "barrel-fit-denim",
    "name": "BARREL FIT DENIM",
    "gender": "male",
    "featuredCategory": "denims",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6DSWD777-CHR_1.jpg?v=1781265458&width=840",
    "category": "lower_body",
    "garment_type": "jeans"
  },
  {
    "id": "kimono-textured-top",
    "name": "KIMONO TEXTURED TOP",
    "gender": "female",
    "featuredCategory": "shirts",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6DSWT770-OFW_1.jpg?v=1779529132&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "straight-fit-pleated-denim",
    "name": "STRAIGHT FIT PLEATED DENIM",
    "gender": "male",
    "featuredCategory": "denims",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6DSWD724-BLU_2.jpg?v=1778581511&width=840",
    "category": "lower_body",
    "garment_type": "jeans"
  },
  {
    "id": "pinstripe-blazer",
    "name": "PINSTRIPE BLAZER",
    "gender": "female",
    "featuredCategory": "shirts",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6DSWT748-BRG_1.jpg?v=1779350835&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "embroidered-japanese-knit-top",
    "name": "EMBROIDERED JAPANESE KNIT TOP",
    "gender": "female",
    "featuredCategory": "shirts",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESNT973-GRN_6.jpg?v=1787390083&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "sashed-kimono-top",
    "name": "SASHED KIMONO TOP",
    "gender": "female",
    "featuredCategory": "shirts",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESNT967-RED_2.jpg?v=1787390088&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "tank-top-with-seam-detail",
    "name": "TANK TOP WITH SEAM DETAIL",
    "gender": "female",
    "featuredCategory": "knit",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESNT948-PNK_4.jpg?v=1787230077&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "graphic-button-down-knit-top",
    "name": "GRAPHIC BUTTON-DOWN KNIT TOP",
    "gender": "female",
    "featuredCategory": "shirts",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESNT938-PNK_7.jpg?v=1787230098&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "graphic-regular-tee",
    "name": "GRAPHIC REGULAR TEE",
    "gender": "male",
    "featuredCategory": "tees",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESNT947-BLU_1.jpg?v=1786534937&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "textured-button-down-top",
    "name": "TEXTURED BUTTON DOWN TOP",
    "gender": "female",
    "featuredCategory": "shirts",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESWT970-BRN_2.jpg?v=1787390021&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "oversized-top-with-sleeve-detail",
    "name": "OVERSIZED TOP WITH SLEEVE DETAIL",
    "gender": "female",
    "featuredCategory": "shirts",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESWT936-BRN_4.jpg?v=1787230052&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "oversized-button-down-shirt",
    "name": "OVERSIZED BUTTON DOWN SHIRT",
    "gender": "male",
    "featuredCategory": "shirts",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESWT961-BLU_2.jpg?v=1786534732&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "button-down-shirt-with-bloused-sleeve",
    "name": "BUTTON DOWN SHIRT WITH BLOUSED SLEEVE",
    "gender": "female",
    "featuredCategory": "shirts",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESWT946-MTO_2.jpg?v=1786534773&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "graphic-top-with-tie-detail",
    "name": "GRAPHIC TOP WITH TIE DETAIL",
    "gender": "female",
    "featuredCategory": "shirts",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESWT915-OFW_1.jpg?v=1786515170&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "cropped-printed-button-down-shirt",
    "name": "CROPPED PRINTED BUTTON DOWN SHIRT",
    "gender": "male",
    "featuredCategory": "shirts",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESWT914-WHT_1.jpg?v=1786515176&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "mega-wide-denim",
    "name": "MEGA WIDE DENIM",
    "gender": "male",
    "featuredCategory": "denims",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESWD943-BLU_1.jpg?v=1787230063&width=840",
    "category": "lower_body",
    "garment_type": "jeans"
  },
  {
    "id": "bootcut-denim",
    "name": "BOOTCUT DENIM",
    "gender": "male",
    "featuredCategory": "denims",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESWD929-BLU_1.jpg?v=1786451174&width=840",
    "category": "lower_body",
    "garment_type": "jeans"
  },
  {
    "id": "wide-leg-denim",
    "name": "WIDE LEG DENIM",
    "gender": "male",
    "featuredCategory": "denims",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESWD949-BLU_1.jpg?v=1786534839&width=840",
    "category": "lower_body",
    "garment_type": "jeans"
  },
  {
    "id": "cropped-top-with-ruched-detail",
    "name": "CROPPED TOP WITH RUCHED DETAIL",
    "gender": "female",
    "featuredCategory": "shirts",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/26FWT328-BRN_1.jpg?v=1787554533&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "wide-leg-trousers",
    "name": "WIDE LEG TROUSERS",
    "gender": "male",
    "featuredCategory": "trousers",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/26FWP328-BRN_1.jpg?v=1787554566&width=840",
    "category": "lower_body",
    "garment_type": "trouser"
  },
  {
    "id": "basic-oversized-tee",
    "name": "BASIC OVERSIZED TEE",
    "gender": "male",
    "featuredCategory": "tees",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/26FNT312-BGE_4.jpg?v=1787554624&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "oversized-top-with-balloon-sleeves",
    "name": "OVERSIZED TOP WITH BALLOON SLEEVES",
    "gender": "female",
    "featuredCategory": "shirts",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/26FWT310-BRN_1.jpg?v=1787554560&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "straight-fit-trousers",
    "name": "STRAIGHT FIT TROUSERS",
    "gender": "male",
    "featuredCategory": "trousers",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/26FWP310-BRN_1.jpg?v=1787554576&width=840",
    "category": "lower_body",
    "garment_type": "trouser"
  },
  {
    "id": "boys-drop-shoulder-chicago-bulls-tee",
    "name": "BOYS DROP SHOULDER CHICAGO BULLS TEE",
    "gender": "boys",
    "featuredCategory": "tees",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K5AST252-KHK_2_bd0af615-08eb-43a2-84c6-cce50d02e701.jpg?v=1756899109&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "boys-drop-shoulder-tee",
    "name": "BOYS DROP SHOULDER TEE",
    "gender": "boys",
    "featuredCategory": "tees",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6DST641-BLU_1.jpg?v=1778504080&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "boys-printed-tank-top",
    "name": "BOYS PRINTED TANK TOP",
    "gender": "boys",
    "featuredCategory": "tees",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K5CST492-MST_1.jpg?v=1756898048&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "boys-striped-tee",
    "name": "BOYS STRIPED TEE",
    "gender": "boys",
    "featuredCategory": "tees",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6DST673-MLT_1.jpg?v=1779280870&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "boys-striper-tee",
    "name": "BOYS STRIPER TEE",
    "gender": "boys",
    "featuredCategory": "tees",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K5DST656-MLT_1.jpg?v=1756897976&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "boys-tie-dye-tee",
    "name": "BOYS TIE & DYE TEE",
    "gender": "boys",
    "featuredCategory": "tees",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K5DST666-MLT_1.jpg?v=1756897915&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "boys-mickey-embroidered-ribbed-tee",
    "name": "BOYS MICKEY EMBROIDERED RIBBED TEE",
    "gender": "boys",
    "featuredCategory": "tees",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6EST807-RED_3.jpg?v=1787230048&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "boys-new-york-tee",
    "name": "BOYS NEW YORK TEE",
    "gender": "boys",
    "featuredCategory": "tees",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6EST696-BLU_2_a4437cf0-d46f-4f2f-9c6e-2be4c7fffe32.jpg?v=1781503002&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "boys-printed-sleeveless-tee",
    "name": "BOYS PRINTED SLEEVELESS TEE",
    "gender": "boys",
    "featuredCategory": "tees",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6EST693-WHT_1_2a7b5498-bcfd-49af-96c6-eef82cbb3400.jpg?v=1781503006&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "boys-graphic-print-boxy-fit-tee",
    "name": "BOYS GRAPHIC PRINT BOXY FIT TEE",
    "gender": "boys",
    "featuredCategory": "tees",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6EST828-DPK_1.jpg?v=1786362189&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "boys-printed-shirt",
    "name": "BOYS PRINTED SHIRT",
    "gender": "boys",
    "featuredCategory": "shirts",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6ESW802-WHT_1.jpg?v=1781265332&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "boys-pocket-detail-shirt",
    "name": "BOYS POCKET DETAIL SHIRT",
    "gender": "boys",
    "featuredCategory": "shirts",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6ESW803-GRE_1.jpg?v=1782107622&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "boys-striped-boxy-fit-shirt",
    "name": "BOYS STRIPED BOXY FIT SHIRT",
    "gender": "boys",
    "featuredCategory": "shirts",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6ESW805-BWT_1.jpg?v=1781265323&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "boys-seer-sucker-shirt",
    "name": "BOYS SEER SUCKER SHIRT",
    "gender": "boys",
    "featuredCategory": "shirts",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6ESW801-GRN_1.jpg?v=1781265336&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "boys-self-checkered-shirt",
    "name": "BOYS SELF CHECKERED SHIRT",
    "gender": "boys",
    "featuredCategory": "shirts",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/6ESW800-BRN_1.jpg?v=1782107693&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "boys-striped-resort-collar-shirt",
    "name": "BOYS STRIPED RESORT COLLAR SHIRT",
    "gender": "boys",
    "featuredCategory": "shirts",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6ESW804-WBR_1.jpg?v=1781265327&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "boys-cargo-shorts",
    "name": "BOYS CARGO SHORTS",
    "gender": "boys",
    "featuredCategory": "bottoms",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6ESB833-BRN_1.jpg?v=1786362425&width=840",
    "category": "lower_body",
    "garment_type": "trouser"
  },
  {
    "id": "boys-chino-shorts",
    "name": "BOYS CHINO SHORTS",
    "gender": "boys",
    "featuredCategory": "bottoms",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6ESB834-KHK_1.jpg?v=1786362410&width=840",
    "category": "lower_body",
    "garment_type": "trouser"
  },
  {
    "id": "boys-knit-cargo-shorts",
    "name": "BOYS KNIT CARGO SHORTS",
    "gender": "boys",
    "featuredCategory": "bottoms",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6ESB828-DIP_1.jpg?v=1786362510&width=840",
    "category": "lower_body",
    "garment_type": "trouser"
  },
  {
    "id": "boys-basic-shorts",
    "name": "BOYS BASIC SHORTS",
    "gender": "boys",
    "featuredCategory": "bottoms",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6ESB814BRN_1.jpg?v=1786362555&width=840",
    "category": "lower_body",
    "garment_type": "trouser"
  },
  {
    "id": "boys-textured-shorts",
    "name": "BOYS TEXTURED SHORTS",
    "gender": "boys",
    "featuredCategory": "bottoms",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6ESB827-BGY_1.jpg?v=1786362516&width=840",
    "category": "lower_body",
    "garment_type": "trouser"
  },
  {
    "id": "boys-utility-denim-shorts",
    "name": "BOYS UTILITY DENIM SHORTS",
    "gender": "boys",
    "featuredCategory": "bottoms",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6ESB829-MBL_1.jpg?v=1786362505&width=840",
    "category": "lower_body",
    "garment_type": "jeans"
  },
  {
    "id": "boys-varsity-graphic-tee",
    "name": "BOYS VARSITY GRAPHIC TEE",
    "gender": "boys",
    "featuredCategory": "tees",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6EST831-BLU_1.jpg?v=1786362183&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "boys-contrast-trim-shorts",
    "name": "BOYS CONTRAST TRIM SHORTS",
    "gender": "boys",
    "featuredCategory": "bottoms",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6ESB831-BLU_1.jpg?v=1786362433&width=840",
    "category": "lower_body",
    "garment_type": "trouser"
  },
  {
    "id": "boys-graphic-print-tee",
    "name": "BOYS GRAPHIC PRINT TEE",
    "gender": "boys",
    "featuredCategory": "tees",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6EST820-BLK_1.jpg?v=1786362201&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "boys-knit-shorts",
    "name": "BOYS KNIT SHORTS",
    "gender": "boys",
    "featuredCategory": "bottoms",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/MUJ7959copy.jpg?v=1786607694&width=840",
    "category": "lower_body",
    "garment_type": "trouser"
  },
  {
    "id": "girls-basic-tights",
    "name": "GIRLS BASIC TIGHTS",
    "gender": "girls",
    "featuredCategory": "bottoms",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K5DSB584-BLU_1_ef869a17-2f39-486f-b798-337fe6e70600.jpg?v=1756897612&width=840",
    "category": "lower_body",
    "garment_type": "trouser"
  },
  {
    "id": "girls-printed-tank-top",
    "name": "GIRLS PRINTED TANK TOP",
    "gender": "girls",
    "featuredCategory": "tops",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6DST580-YEL_1.jpg?v=1778504123&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "girls-mom-fit-denim",
    "name": "GIRLS MOM FIT DENIM",
    "gender": "girls",
    "featuredCategory": "bottoms",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6DSD723-DBL_1.jpg?v=1779280905&width=840",
    "category": "lower_body",
    "garment_type": "jeans"
  },
  {
    "id": "girls-mom-fit-ripped-denim",
    "name": "GIRLS MOM FIT RIPPED DENIM",
    "gender": "girls",
    "featuredCategory": "bottoms",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6DSD704-BLU_1.jpg?v=1778848263&width=840",
    "category": "lower_body",
    "garment_type": "jeans"
  },
  {
    "id": "girls-embellished-studded-tank-top",
    "name": "GIRLS EMBELLISHED STUDDED TANK TOP",
    "gender": "girls",
    "featuredCategory": "tops",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6DST734-BLU_1.jpg?v=1779529616&width=840",
    "category": "upper_body",
    "garment_type": "tshirt"
  },
  {
    "id": "girls-embroidered-flower-striped-dress",
    "name": "GIRLS EMBROIDERED FLOWER STRIPED DRESS",
    "gender": "girls",
    "featuredCategory": "tops",
    "bestSeller": true,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6DST581-EBR_1.jpg?v=1778504120&width=840",
    "category": "full_body",
    "garment_type": "dress"
  },
  {
    "id": "girls-boxy-striped-t-shirt",
    "name": "GIRLS BOXY STRIPED T-SHIRT",
    "gender": "girls",
    "featuredCategory": "frocks",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6EST739-WHT_1.jpg?v=1782107660&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "girls-boxy-embroidered-t-shirt",
    "name": "GIRLS BOXY EMBROIDERED T-SHIRT",
    "gender": "girls",
    "featuredCategory": "frocks",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6EST742-RST_1.jpg?v=1786362233&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "girls-striped-boxy-fit-polo",
    "name": "GIRLS STRIPED BOXY FIT POLO",
    "gender": "girls",
    "featuredCategory": "tops",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6EST750-PnN_1.jpg?v=1786362216&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "girls-floral-printed-knit-playsuit",
    "name": "GIRLS FLORAL PRINTED KNIT PLAYSUIT",
    "gender": "girls",
    "featuredCategory": "coords",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6EST741-PNK_1.jpg?v=1782107647&width=840",
    "category": "full_body",
    "garment_type": "dress"
  },
  {
    "id": "girls-unicorn-t-shirt",
    "name": "GIRLS UNICORN T-SHIRT",
    "gender": "girls",
    "featuredCategory": "frocks",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6EST740-WHT_1.jpg?v=1782107654&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "girls-tropical-t-shirt",
    "name": "GIRLS TROPICAL T-SHIRT",
    "gender": "girls",
    "featuredCategory": "frocks",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6EST744-WHT_1.jpg?v=1786362224&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "girls-denim-embroidered-top",
    "name": "GIRLS DENIM EMBROIDERED TOP",
    "gender": "girls",
    "featuredCategory": "frocks",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6ESW749-LBL_1.jpg?v=1786362175&width=840",
    "category": "lower_body",
    "garment_type": "jeans"
  },
  {
    "id": "girls-printed-cut-sew-dress",
    "name": "GIRLS PRINTED CUT & SEW DRESS",
    "gender": "girls",
    "featuredCategory": "tops",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6DSW570-MLT_1.jpg?v=1778658694&width=840",
    "category": "full_body",
    "garment_type": "dress"
  },
  {
    "id": "girls-stripered-boxy-top",
    "name": "GIRLS STRIPERED BOXY TOP",
    "gender": "girls",
    "featuredCategory": "frocks",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K5ESW740-MLT_1_49d7b5b8-b087-4410-b49e-38de7aa93910.jpg?v=1756900968&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "girls-printed-elasticated-band-dress",
    "name": "GIRLS PRINTED ELASTICATED BAND DRESS",
    "gender": "girls",
    "featuredCategory": "tops",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K5ASW300-NYL_3.jpg?v=1756898988&width=840",
    "category": "full_body",
    "garment_type": "dress"
  },
  {
    "id": "girls-lace-printed-top",
    "name": "GIRLS LACE PRINTED TOP",
    "gender": "girls",
    "featuredCategory": "frocks",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6DSW709-MLT_1_ac4c9f2d-d00d-47ec-b25f-b9d29e3e82b3.jpg?v=1780392804&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "girls-striped-sleeveless-dress",
    "name": "GIRLS STRIPED SLEEVELESS DRESS",
    "gender": "girls",
    "featuredCategory": "tops",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6DSW598-MLT_1.jpg?v=1787046671&width=840",
    "category": "full_body",
    "garment_type": "dress"
  },
  {
    "id": "girls-denim-look-boot-cut-jeggings",
    "name": "GIRLS DENIM LOOK BOOT CUT JEGGINGS",
    "gender": "girls",
    "featuredCategory": "bottoms",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6ESD746-DBL_1.jpg?v=1786362402&width=840",
    "category": "lower_body",
    "garment_type": "jeans"
  },
  {
    "id": "girls-pleated-skirt",
    "name": "GIRLS PLEATED SKIRT",
    "gender": "girls",
    "featuredCategory": "bottoms",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6ESB747-BLK_1.jpg?v=1786362588&width=840",
    "category": "lower_body",
    "garment_type": "trouser"
  },
  {
    "id": "girls-contrast-tipping-shorts",
    "name": "GIRLS CONTRAST TIPPING SHORTS",
    "gender": "girls",
    "featuredCategory": "bottoms",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6ESB751-BLU_1.jpg?v=1786362578&width=840",
    "category": "lower_body",
    "garment_type": "trouser"
  },
  {
    "id": "girls-loose-denim-capri",
    "name": "GIRLS LOOSE DENIM CAPRI",
    "gender": "girls",
    "featuredCategory": "bottoms",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6ESD745-MDB_1.jpg?v=1786362406&width=840",
    "category": "lower_body",
    "garment_type": "jeans"
  },
  {
    "id": "girls-wavy-knit-shorts",
    "name": "GIRLS WAVY KNIT SHORTS",
    "gender": "girls",
    "featuredCategory": "bottoms",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6ESB743-YEL_1.jpg?v=1786362593&width=840",
    "category": "lower_body",
    "garment_type": "trouser"
  },
  {
    "id": "girls-knit-shorts",
    "name": "GIRLS KNIT SHORTS",
    "gender": "girls",
    "featuredCategory": "bottoms",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6ESB742-RST_1.jpg?v=1786362598&width=840",
    "category": "lower_body",
    "garment_type": "trouser"
  },
  {
    "id": "girls-embellished-t-shirt",
    "name": "GIRLS EMBELLISHED T-SHIRT",
    "gender": "girls",
    "featuredCategory": "frocks",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6EST743-YEL_1.jpg?v=1786362228&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  },
  {
    "id": "girls-special-knit-button-down-polo",
    "name": "GIRLS SPECIAL KNIT BUTTON DOWN POLO",
    "gender": "girls",
    "featuredCategory": "tops",
    "bestSeller": false,
    "onSale": false,
    "price": 3899,
    "compareAt": null,
    "image": "https://www.breakout.com.pk/cdn/shop/files/K6EST751-BLU_1.jpg?v=1786362212&width=840",
    "category": "upper_body",
    "garment_type": "shirt"
  }
];

function getProduct(id) {
  return PRODUCTS.find((p) => p.id === id) || null;
}

function getProducts(gender, featuredCategoryId) {
  return PRODUCTS.filter(
    (p) =>
      p.gender === gender &&
      (!featuredCategoryId || p.featuredCategory === featuredCategoryId)
  );
}

function getBestSellers(gender, limit = 6) {
  const sellers = PRODUCTS.filter((p) => p.gender === gender && p.bestSeller);
  return sellers.length ? sellers.slice(0, limit) : PRODUCTS.filter((p) => p.gender === gender).slice(0, limit);
}

function formatPrice(amount) {
  return "PKR " + amount.toLocaleString("en-PK");
}

function formatPriceHtml(product) {
  if (product.onSale && product.compareAt) {
    return (
      `<span class="price-sale">Sale price:${formatPrice(product.price)}</span>` +
      `<span class="price-compare">Regular price: <s>${formatPrice(product.compareAt)}</s></span>`
    );
  }
  return `<span class="price-regular">Price:${formatPrice(product.price)}</span>`;
}
