/**
 * Product catalog for the outfit store.
 *
 * Store fields (shown in the shop): name, price, storeCategory, image, …
 * VTON fields (hidden, sent to API later): category (vton_type), garment_type
 */

const STORE_CATEGORIES = [
  { id: "tops", label: "Tops & Shirts" },
  { id: "bottoms", label: "Pants & Bottoms" },
  { id: "outfits", label: "Outfits & Sets" },
];

const PRODUCTS = [
  {
    id: "m-shirt-blue",
    name: "Blue Formal Shirt",
    gender: "male",
    storeCategory: "tops",
    category: "upper_body",
    garment_type: "shirt",
    price: 2499,
    color: "#3b6ea5",
    image: "images/m-shirt-blue.jpg",
    description: "Classic blue cotton shirt",
  },
  {
    id: "m-tshirt-white",
    name: "White T-Shirt",
    gender: "male",
    storeCategory: "tops",
    category: "upper_body",
    garment_type: "tshirt",
    price: 899,
    color: "#f0f0f0",
    image: "images/m-tshirt-white.jpg",
    description: "Plain white crew-neck tee",
  },
  {
    id: "m-kurta-cream",
    name: "Cream Kurta",
    gender: "male",
    storeCategory: "tops",
    category: "upper_body",
    garment_type: "kurta",
    price: 3499,
    color: "#e8dcc8",
    image: "images/m-kurta-cream.jpg",
    description: "Long kurta with side slits",
  },
  {
    id: "m-jeans-dark",
    name: "Dark Jeans",
    gender: "male",
    storeCategory: "bottoms",
    category: "lower_body",
    garment_type: "jeans",
    price: 2799,
    color: "#2c3e6b",
    image: "images/m-jeans-dark.jpg",
    description: "Slim-fit dark wash denim",
  },
  {
    id: "m-trouser-grey",
    name: "Grey Trousers",
    gender: "male",
    storeCategory: "bottoms",
    category: "lower_body",
    garment_type: "trouser",
    price: 2299,
    color: "#6b7280",
    image: "images/m-trouser-grey.jpg",
    description: "Formal grey trousers",
  },
  {
    id: "m-shorts-khaki",
    name: "Khaki Shorts",
    gender: "male",
    storeCategory: "bottoms",
    category: "lower_body",
    garment_type: "shorts",
    price: 1499,
    color: "#b5a642",
    image: "images/m-shorts-khaki.jpg",
    description: "Casual summer shorts",
  },
  {
    id: "m-suit-navy",
    name: "Navy Suit",
    gender: "male",
    storeCategory: "outfits",
    category: "full_body",
    garment_type: "suit",
    price: 12999,
    color: "#1e3a5f",
    image: "images/m-suit-navy.jpg",
    description: "Two-piece navy business suit",
  },
  {
    id: "m-shirt-pant-set",
    name: "Shirt + Pant Set",
    gender: "male",
    storeCategory: "outfits",
    category: "full_body",
    garment_type: "shirt_pant",
    price: 4999,
    color: "#4a7c59",
    image: "images/m-shirt-pant-set.jpg",
    description: "Coordinated shirt and pant outfit",
  },
  {
    id: "m-kurta-shalwar",
    name: "Kurta Shalwar",
    gender: "male",
    storeCategory: "outfits",
    category: "full_body",
    garment_type: "kurta_shalwar",
    price: 5999,
    color: "#8b7355",
    image: "images/m-kurta-shalwar.jpg",
    description: "Traditional kurta with shalwar",
  },
  {
    id: "f-blouse-white",
    name: "White Blouse",
    gender: "female",
    storeCategory: "tops",
    category: "upper_body",
    garment_type: "shirt",
    price: 2199,
    color: "#fafafa",
    image: "images/f-blouse-white.jpg",
    description: "Elegant white blouse",
  },
  {
    id: "f-tshirt-pink",
    name: "Pink T-Shirt",
    gender: "female",
    storeCategory: "tops",
    category: "upper_body",
    garment_type: "tshirt",
    price: 799,
    color: "#f4a4b8",
    image: "images/f-tshirt-pink.jpg",
    description: "Soft pink casual tee",
  },
  {
    id: "f-kurta-embroidered",
    name: "Embroidered Kurta",
    gender: "female",
    storeCategory: "tops",
    category: "upper_body",
    garment_type: "kurta",
    price: 4299,
    color: "#c9a87c",
    image: "images/f-kurta-embroidered.jpg",
    description: "Embroidered long kurta",
  },
  {
    id: "f-jeans-light",
    name: "Light Jeans",
    gender: "female",
    storeCategory: "bottoms",
    category: "lower_body",
    garment_type: "jeans",
    price: 2599,
    color: "#7ba3c9",
    image: "images/f-jeans-light.jpg",
    description: "High-waist light wash jeans",
  },
  {
    id: "f-trouser-black",
    name: "Black Trousers",
    gender: "female",
    storeCategory: "bottoms",
    category: "lower_body",
    garment_type: "trouser",
    price: 2399,
    color: "#2d2d2d",
    image: "images/f-trouser-black.jpg",
    description: "Tailored black trousers",
  },
  {
    id: "f-shalwar-white",
    name: "White Shalwar",
    gender: "female",
    storeCategory: "bottoms",
    category: "lower_body",
    garment_type: "shalwar",
    price: 1799,
    color: "#f5f5f0",
    image: "images/f-shalwar-white.jpg",
    description: "Loose white shalwar",
  },
  {
    id: "f-dress-red",
    name: "Red Dress",
    gender: "female",
    storeCategory: "outfits",
    category: "full_body",
    garment_type: "dress",
    price: 5499,
    color: "#c0392b",
    image: "images/f-dress-red.jpg",
    description: "Midi red dress",
  },
  {
    id: "f-kurta-shalwar-set",
    name: "Kurta Shalwar Set",
    gender: "female",
    storeCategory: "outfits",
    category: "full_body",
    garment_type: "kurta_shalwar",
    price: 6499,
    color: "#9b7bb8",
    image: "images/f-kurta-shalwar-set.jpg",
    description: "Matching kurta and shalwar",
  },
  {
    id: "f-shirt-pant-outfit",
    name: "Shirt + Pant Outfit",
    gender: "female",
    storeCategory: "outfits",
    category: "full_body",
    garment_type: "shirt_pant",
    price: 4799,
    color: "#5d8a66",
    image: "images/f-shirt-pant-outfit.jpg",
    description: "Casual coordinated outfit",
  },
];

function getProduct(id) {
  return PRODUCTS.find((p) => p.id === id) || null;
}

function getProducts(gender, storeCategoryId) {
  return PRODUCTS.filter(
    (p) =>
      p.gender === gender &&
      (!storeCategoryId || p.storeCategory === storeCategoryId)
  );
}

function formatPrice(amount) {
  return "Rs " + amount.toLocaleString("en-PK");
}
