/** Midnight Editorial design tokens from Stitch project 9894339067076282409 */
window.ELITE_TAILWIND = {
  colors: {
    primary: "#041627",
    "on-error": "#ffffff",
    error: "#ba1a1a",
    "on-primary-fixed": "#0b1d2d",
    "on-secondary-fixed-variant": "#46464e",
    "secondary-fixed": "#e3e1ec",
    "tertiary-fixed": "#e2e2e3",
    "surface-dim": "#dcd9dc",
    "on-secondary-fixed": "#1a1b22",
    tertiary: "#141617",
    "inverse-on-surface": "#f3f0f2",
    "on-tertiary": "#ffffff",
    "primary-fixed-dim": "#b7c8de",
    "tertiary-fixed-dim": "#c6c6c7",
    background: "#fcf8fb",
    "surface-bright": "#fcf8fb",
    "surface-tint": "#4f6073",
    "primary-container": "#1a2b3c",
    "inverse-surface": "#313032",
    "surface-container-high": "#eae7ea",
    surface: "#fcf8fb",
    "on-secondary": "#ffffff",
    "surface-container": "#f0edf0",
    "tertiary-container": "#282a2b",
    "on-primary": "#ffffff",
    "on-tertiary-container": "#909192",
    "surface-container-highest": "#e5e1e4",
    outline: "#74777d",
    "on-primary-fixed-variant": "#38485a",
    "on-tertiary-fixed": "#1a1c1d",
    "on-background": "#1c1b1d",
    "outline-variant": "#c4c6cd",
    "surface-container-lowest": "#ffffff",
    "surface-container-low": "#f6f2f5",
    "on-surface-variant": "#44474c",
    secondary: "#5d5e66",
    "secondary-fixed-dim": "#c6c5cf",
    "inverse-primary": "#b7c8de",
    "secondary-container": "#e3e1ec",
    "on-tertiary-fixed-variant": "#454748",
    "surface-variant": "#e5e1e4",
    "on-error-container": "#93000a",
    "on-surface": "#1c1b1d",
    "on-secondary-container": "#63646c",
    "primary-fixed": "#d2e4fb",
    "error-container": "#ffdad6",
    "on-primary-container": "#8192a7",
    scrim: "rgba(4, 22, 39, 0.4)",
  },
  borderRadius: {
    DEFAULT: "0.25rem",
    lg: "0.5rem",
    xl: "0.75rem",
    full: "9999px",
  },
  spacing: {
    gutter: "16px",
    "stack-sm": "8px",
    "container-padding": "20px",
    unit: "4px",
    "stack-lg": "48px",
    "stack-md": "24px",
  },
  fontFamily: {
    "label-lg": ["Inter", "sans-serif"],
    "headline-md": ["Playfair Display", "serif"],
    "body-sm": ["Inter", "sans-serif"],
    "label-md": ["Inter", "sans-serif"],
    "headline-lg": ["Playfair Display", "serif"],
    "headline-lg-mobile": ["Playfair Display", "serif"],
    "display-lg": ["Playfair Display", "serif"],
    "body-lg": ["Inter", "sans-serif"],
    "body-md": ["Inter", "sans-serif"],
  },
  fontSize: {
    "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
    "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
    "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
    "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
    "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
    "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
    "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
    "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
    "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
  },
};
